name: eye_for_eye
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.8
  - pip:
    - matplotlib==3.6.3
    - matplotlib-inline==0.1.6
    - jupyter==1.0.0
    - numpy==1.24.1
    - pyrallis==0.3.1
    - torch==2.1.0 --index-url https://download.pytorch.org/whl/cu118
    - torchvision==0.16.0 --index-url https://download.pytorch.org/whl/cu118
    - diffusers==0.19.3
    - transformers==4.30.2
    - accelerate==0.20.3
    - huggingface-hub==0.16.4
    - xformers==0.0.22.post4 --index-url https://download.pytorch.org/whl/cu118
    - tokenizers==0.13.3
    - nltk==3.8.1
    - Pillow==10.1.0
    - scikit_learn==1.3.0
    - tqdm==4.64.1
